name: Cleanup Old Deployments

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  
  workflow_dispatch:

jobs:
  cleanup:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Delete Old Deployments
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const environments = ['production', 'development', 'Preview', 'finance-tracker (generous-wonder / development)', 'faithful-ambition (generous-wonder / production)']; 

            for (const environment of environments) {
              const { data: deployments } = await github.rest.repos.listDeployments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment: environment
              });

              if (deployments.length < 2) {
                console.log(`There are less than 2 deployments in ${environment}, nothing to delete.`);
                continue;  
              }

              deployments.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

              const deploymentsToDelete = deployments.slice(2);

              for (const deployment of deploymentsToDelete) {
                try {
                  // Primero intentar marcarlo como inactivo
                  await github.rest.repos.createDeploymentStatus({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    deployment_id: deployment.id,
                    state: 'inactive'
                  });

                  console.log(`Marked deployment ${deployment.id} as inactive.`);

                  await github.rest.repos.deleteDeployment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    deployment_id: deployment.id
                  });

                  console.log(`Deleted deployment ${deployment.id} from ${environment}`);
                } catch (error) {
                  console.log(`❌ Could not delete deployment ${deployment.id}: ${error.message}`);
                }
              }
            }
