name: Cleanup Old Deployments

on:
  pull_request:
    types:
      - closed
    branches:
      - main 

jobs:
  cleanup:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest

    steps:
      - name: Delete Old Deployments
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const environments = ['production', 'development', 'Preview']; 

            for (const environment of environments) {
              const { data: deployments } = await github.rest.repos.listDeployments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment: environment
              });

              if (deployments.length < 2) {
                console.log(`There are less than 2 deployments in ${environment}, nothing to delete.`);
                continue;  
              }

              // Ordenar deployments por fecha (más reciente primero)
              deployments.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

              // Mantener solo los dos más recientes
              const deploymentsToDelete = deployments.slice(2);  // Eliminar todo excepto los dos más recientes

              for (const deployment of deploymentsToDelete) {
                console.log(`Deleting deployment ID ${deployment.id} from environment: ${environment}`);
                await github.rest.repos.deleteDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  deployment_id: deployment.id
                });
              }
            }
